# Generated by Django 5.1.2 on 2024-11-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('id_prov', models.IntegerField()),
                ('id_suc', models.IntegerField()),
            ],
        ),
    ]
