# Generated by Django 5.1.2 on 2024-11-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_pr', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='Nombre del Empleado')),
                ('tel', models.CharField(max_length=11)),
                ('cor', models.EmailField(max_length=100, verbose_name='correo')),
                ('dir', models.CharField(max_length=100, verbose_name='direccion')),
                ('stock', models.BigIntegerField(max_length=100, verbose_name='Salario')),
                ('cal', models.PositiveSmallIntegerField(max_length=100, verbose_name='Calificación')),
            ],
        ),
    ]
