# Generated by Django 5.1.2 on 2024-11-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_suc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Sucursal')),
                ('dire', models.CharField(max_length=100, verbose_name='Direccion de la Sucursal')),
                ('horario', models.TimeField()),
                ('tel', models.CharField(max_length=100, verbose_name='telefono')),
                ('correo', models.EmailField(max_length=100, verbose_name='correo')),
            ],
        ),
    ]
